number1=input('please tell me  number: ')
number2=input('please tell me second number: ')

print(int(number1)+int(number2))
print(int(number1)-int(number2))
print(int(number1)*int(number2))
print(int(number1)/int(number2))
print(int(number1)//int(number2))
print(int(number1)%int(number2))
print(int(number1)>int(number2))
print(int(number1)<int(number2))
print(int(number1)==int(number2))
print(float(number2))
print(float(number1))
print(float(number1)+3)
print((number2)+ "5")
print(float(number1)+6)
print(int(number2)+2.3)